const translations = {
    en: {
        nav_home: "Home",
        nav_ecosystem: "Ecosystem",
        nav_dashboard: "Dashboard",
        hero_badge: "🚀 Launch 2026",
        hero_title1: "Decentralized",
        hero_title2: "Taxi of the Future",
        hero_desc: "$TAXI — the first token on Solana for a global taxi, delivery, and logistics platform. Earn, vote, and get up to 50% discounts.",
        stat_mcap: "Market Cap",
        stat_supply: "Total Supply",
        stat_price: "Initial Price",
        btn_buy: "Buy $TAXI →",
        btn_learn: "Learn More",
        features_title1: "Why",
        features_title2: "$TAXI",
        features_title3: "?",
        feature1_title: "Instant Transactions",
        feature1_desc: "Solana delivers 400ms speed and fees < $0.001",
        feature2_title: "Full Security",
        feature2_desc: "Token-2022 standard with advanced security features",
        feature3_title: "Global Ecosystem",
        feature3_desc: "6 satellite tokens for different regions and use cases",
        feature4_title: "Decentralized Governance",
        feature4_desc: "DAO with voting rights for $DHL holders",
        exchange_title1: "Exchange Rates in",
        exchange_title2: "Ecosystem",
        exchange1: "Tips & Acceleration",
        exchange2: "Staking & Discounts",
        exchange3: "DAO Governance",
        exchange4: "Business Class",
        solana_powered: "Powered by",
        footer_desc: "Decentralized taxi & delivery platform on Solana",
        footer_tokens: "Tokens",
        footer_resources: "Resources",
        footer_docs: "Documentation",
        footer_whitepaper: "Whitepaper",
        footer_github: "GitHub",
        footer_contact: "Contact",
        footer_partners: "Partnership",
        footer_rights: "All rights reserved.",
        eco_title: "🌍 $TAXI Ecosystem",
        eco_sub: "6 interconnected tokens for a global decentralized platform",
        taxi_role: "⭐ Main Ecosystem Token",
        taxi_price: "Price",
        taxi_supply: "Supply",
        taxi_cap: "Market Cap",
        taxi_address: "Address",
        taxi_buy: "Buy",
        taxi_pools: "Pools",
        taxi_staking: "Staking",
        sat_title: "🛰️ Satellite",
        sat_title2: "Tokens",
        uber_desc: "Unified Blockchain Express Ride — staking and up to 30% discounts. Access to business class and priority calls.",
        dhl_desc: "Decentralized Haul Ledger — ecosystem governance. Voting for cities, fees, and budget.",
        tip_desc: "Transaction Incentive Program — universal tip token for taxis, cafes, restaurants, hotels.",
        fdx_desc: "Fuel eXchange — reserved for fuel pools, B2B logistics, and carbon credits in 2030.",
        didi_desc: "Decentralized Intelligent Driving Infrastructure — regional token for China and East Asia.",
        grab_desc: "Global Ride and App-Based — regional token for Southeast Asia (ASEAN).",
        map_title: "🗺️ Ecosystem",
        map_title2: "Map",
        regional_title: "🌏 Regional",
        regional_title2: "Tokens",
        didi_region: "China, Japan, Korea, Taiwan",
        grab_region: "Singapore, Malaysia, Thailand, Vietnam, Indonesia",
        dash_title: "📊 $TAXI",
        dash_title2: "Dashboard",
        dash_sub: "Real-time prices, volumes, and ecosystem statistics",
        stat_24h: "24h Volume",
        stat_holders: "Holders",
        stat_tvl: "TVL",
        chart_title: "📈 $TAXI Price",
        all_tokens: "All Ecosystem",
        all_tokens2: "Tokens",
        token_col: "Token",
        price_col: "Price",
        change_col: "24h %",
        cap_col: "Market Cap",
        action_col: "Action",
        trade_btn: "Trade",
        soon_btn: "Soon",
        wallet_title: "🔐 Your Wallet",
        connect_wallet: "Connect Wallet"
    },
    'zh-CN': {
        nav_home: "首页",
        nav_ecosystem: "生态系统",
        nav_dashboard: "仪表盘",
        hero_badge: "🚀 2026年启动",
        hero_title1: "去中心化",
        hero_title2: "未来出租车",
        hero_desc: "$TAXI — Solana上首个全球出租车、配送和物流平台代币。赚取收益、投票并获得高达50%的折扣。",
        stat_mcap: "市值",
        stat_supply: "总供应量",
        stat_price: "初始价格",
        btn_buy: "购买 $TAXI →",
        btn_learn: "了解更多",
        features_title1: "为什么选择",
        features_title2: "$TAXI",
        features_title3: "？",
        feature1_title: "即时交易",
        feature1_desc: "Solana提供400毫秒速度和低于$0.001的费用",
        feature2_title: "完全安全",
        feature2_desc: "Token-2022标准，配备高级安全功能",
        feature3_title: "全球生态系统",
        feature3_desc: "6个卫星代币，面向不同地区和用例",
        feature4_title: "去中心化治理",
        feature4_desc: "DAO，$DHL持有者拥有投票权",
        exchange_title1: "生态系统中的",
        exchange_title2: "汇率",
        exchange1: "小费和加速",
        exchange2: "质押和折扣",
        exchange3: "DAO治理",
        exchange4: "商务舱",
        solana_powered: "由以下技术支持",
        footer_desc: "Solana上的去中心化出租车和配送平台",
        footer_tokens: "代币",
        footer_resources: "资源",
        footer_docs: "文档",
        footer_whitepaper: "白皮书",
        footer_github: "GitHub",
        footer_contact: "联系方式",
        footer_partners: "合作伙伴",
        footer_rights: "保留所有权利。",
        eco_title: "🌍 $TAXI 生态系统",
        eco_sub: "6个互联代币，构建全球去中心化平台",
        taxi_role: "⭐ 生态系统主代币",
        taxi_price: "价格",
        taxi_supply: "供应量",
        taxi_cap: "市值",
        taxi_address: "地址",
        taxi_buy: "购买",
        taxi_pools: "池子",
        taxi_staking: "质押",
        sat_title: "🛰️ 卫星",
        sat_title2: "代币",
        uber_desc: "统一区块链快车 — 质押并享受高达30%的折扣。可访问商务舱和优先叫车。",
        dhl_desc: "去中心化运输账本 — 生态系统治理。对城市、费用和预算进行投票。",
        tip_desc: "交易激励计划 — 用于出租车、咖啡馆、餐厅、酒店的通用小费代币。",
        fdx_desc: "燃料交易所 — 为2030年的燃料池、B2B物流和碳信用预留。",
        didi_desc: "去中心化智能驾驶基础设施 — 中国和东亚的区域代币。",
        grab_desc: "全球出行和应用程序 — 东南亚（东盟）的区域代币。",
        map_title: "🗺️ 生态系统",
        map_title2: "地图",
        regional_title: "🌏 区域",
        regional_title2: "代币",
        didi_region: "中国、日本、韩国、台湾",
        grab_region: "新加坡、马来西亚、泰国、越南、印度尼西亚",
        dash_title: "📊 $TAXI",
        dash_title2: "仪表盘",
        dash_sub: "实时价格、交易量和生态系统统计数据",
        stat_24h: "24小时交易量",
        stat_holders: "持有者",
        stat_tvl: "总锁定价值",
        chart_title: "📈 $TAXI 价格",
        all_tokens: "所有生态系统",
        all_tokens2: "代币",
        token_col: "代币",
        price_col: "价格",
        change_col: "24小时变化",
        cap_col: "市值",
        action_col: "操作",
        trade_btn: "交易",
        soon_btn: "即将推出",
        wallet_title: "🔐 您的钱包",
        connect_wallet: "连接钱包"
    },
    'zh-TW': {
        nav_home: "首頁",
        nav_ecosystem: "生態系統",
        nav_dashboard: "儀表板",
        hero_badge: "🚀 2026年啟動",
        hero_title1: "去中心化",
        hero_title2: "未來計程車",
        hero_desc: "$TAXI — Solana上首個全球計程車、配送和物流平台代幣。賺取收益、投票並獲得高達50%的折扣。",
        stat_mcap: "市值",
        stat_supply: "總供應量",
        stat_price: "初始價格",
        btn_buy: "購買 $TAXI →",
        btn_learn: "了解更多",
        features_title1: "為什麼選擇",
        features_title2: "$TAXI",
        features_title3: "？",
        feature1_title: "即時交易",
        feature1_desc: "Solana提供400毫秒速度和低於$0.001的費用",
        feature2_title: "完全安全",
        feature2_desc: "Token-2022標準，配備高級安全功能",
        feature3_title: "全球生態系統",
        feature3_desc: "6個衛星代幣，面向不同地區和用例",
        feature4_title: "去中心化治理",
        feature4_desc: "DAO，$DHL持有者擁有投票權",
        exchange_title1: "生態系統中的",
        exchange_title2: "匯率",
        exchange1: "小費和加速",
        exchange2: "質押和折扣",
        exchange3: "DAO治理",
        exchange4: "商務艙",
        solana_powered: "由以下技術支持",
        footer_desc: "Solana上的去中心化計程車和配送平台",
        footer_tokens: "代幣",
        footer_resources: "資源",
        footer_docs: "文檔",
        footer_whitepaper: "白皮書",
        footer_github: "GitHub",
        footer_contact: "聯繫方式",
        footer_partners: "合作夥伴",
        footer_rights: "保留所有權利。",
        eco_title: "🌍 $TAXI 生態系統",
        eco_sub: "6個互聯代幣，構建全球去中心化平台",
        taxi_role: "⭐ 生態系統主代幣",
        taxi_price: "價格",
        taxi_supply: "供應量",
        taxi_cap: "市值",
        taxi_address: "地址",
        taxi_buy: "購買",
        taxi_pools: "池子",
        taxi_staking: "質押",
        sat_title: "🛰️ 衛星",
        sat_title2: "代幣",
        uber_desc: "統一區塊鏈快車 — 質押並享受高達30%的折扣。可訪問商務艙和優先叫車。",
        dhl_desc: "去中心化運輸帳本 — 生態系統治理。對城市、費用和預算進行投票。",
        tip_desc: "交易激勵計劃 — 用於計程車、咖啡館、餐廳、酒店的通用小費代幣。",
        fdx_desc: "燃料交易所 — 為2030年的燃料池、B2B物流和碳信用預留。",
        didi_desc: "去中心化智能駕駛基礎設施 — 中國和東亞的區域代幣。",
        grab_desc: "全球出行和應用程序 — 東南亞（東盟）的區域代幣。",
        map_title: "🗺️ 生態系統",
        map_title2: "地圖",
        regional_title: "🌏 區域",
        regional_title2: "代幣",
        didi_region: "中國、日本、韓國、台灣",
        grab_region: "新加坡、馬來西亞、泰國、越南、印度尼西亞",
        dash_title: "📊 $TAXI",
        dash_title2: "儀表板",
        dash_sub: "實時價格、交易量和生態系統統計數據",
        stat_24h: "24小時交易量",
        stat_holders: "持有者",
        stat_tvl: "總鎖定價值",
        chart_title: "📈 $TAXI 價格",
        all_tokens: "所有生態系統",
        all_tokens2: "代幣",
        token_col: "代幣",
        price_col: "價格",
        change_col: "24小時變化",
        cap_col: "市值",
        action_col: "操作",
        trade_btn: "交易",
        soon_btn: "即將推出",
        wallet_title: "🔐 您的錢包",
        connect_wallet: "連接錢包"
    },
    ja: {
        nav_home: "ホーム",
        nav_ecosystem: "エコシステム",
        nav_dashboard: "ダッシュボード",
        hero_badge: "🚀 2026年ローンチ",
        hero_title1: "分散型",
        hero_title2: "未来のタクシー",
        hero_desc: "$TAXI — Solana上のグローバルタクシー、配達、物流プラットフォームの最初のトークン。収益を得て、投票し、最大50%の割引を受ける。",
        stat_mcap: "時価総額",
        stat_supply: "総供給量",
        stat_price: "初期価格",
        btn_buy: "$TAXIを購入 →",
        btn_learn: "詳細を見る",
        features_title1: "なぜ",
        features_title2: "$TAXI",
        features_title3: "なのか？",
        feature1_title: "瞬時取引",
        feature1_desc: "Solanaは400msの速度と$0.001未満の手数料を実現",
        feature2_title: "完全なセキュリティ",
        feature2_desc: "Token-2022標準と高度なセキュリティ機能",
        feature3_title: "グローバルエコシステム",
        feature3_desc: "6つのサテライトトークンが異なる地域とユースケースに対応",
        feature4_title: "分散型ガバナンス",
        feature4_desc: "$DHL保有者が投票権を持つDAO",
        exchange_title1: "エコシステム内の",
        exchange_title2: "為替レート",
        exchange1: "チップと加速",
        exchange2: "ステーキングと割引",
        exchange3: "DAOガバナンス",
        exchange4: "ビジネスクラス",
        solana_powered: "搭載",
        footer_desc: "Solana上の分散型タクシー＆配達プラットフォーム",
        footer_tokens: "トークン",
        footer_resources: "リソース",
        footer_docs: "ドキュメント",
        footer_whitepaper: "ホワイトペーパー",
        footer_github: "GitHub",
        footer_contact: "連絡先",
        footer_partners: "パートナーシップ",
        footer_rights: "全著作権所有。",
        eco_title: "🌍 $TAXI エコシステム",
        eco_sub: "6つの相互接続されたトークンがグローバルな分散型プラットフォームを構築",
        taxi_role: "⭐ メインエコシステムトークン",
        taxi_price: "価格",
        taxi_supply: "供給量",
        taxi_cap: "時価総額",
        taxi_address: "アドレス",
        taxi_buy: "購入",
        taxi_pools: "プール",
        taxi_staking: "ステーキング",
        sat_title: "🛰️ サテライト",
        sat_title2: "トークン",
        uber_desc: "統合ブロックチェーンエクスプレスライド — ステーキングと最大30%の割引。ビジネスクラスと優先呼び出しへのアクセス。",
        dhl_desc: "分散型輸送台帳 — エコシステムガバナンス。都市、手数料、予算への投票。",
        tip_desc: "取引インセンティブプログラム — タクシー、カフェ、レストラン、ホテル向けの汎用チップトークン。",
        fdx_desc: "燃料取引所 — 2030年の燃料プール、B2B物流、カーボンクレジット用に予約。",
        didi_desc: "分散型スマート運転インフラ — 中国と東アジアの地域トークン。",
        grab_desc: "グローバルライド＆アプリベース — 東南アジア（ASEAN）の地域トークン。",
        map_title: "🗺️ エコシステム",
        map_title2: "マップ",
        regional_title: "🌏 地域",
        regional_title2: "トークン",
        didi_region: "中国、日本、韓国、台湾",
        grab_region: "シンガポール、マレーシア、タイ、ベトナム、インドネシア",
        dash_title: "📊 $TAXI",
        dash_title2: "ダッシュボード",
        dash_sub: "リアルタイムの価格、出来高、エコシステム統計",
        stat_24h: "24時間出来高",
        stat_holders: "保有者",
        stat_tvl: "TVL",
        chart_title: "📈 $TAXI 価格",
        all_tokens: "全エコシステム",
        all_tokens2: "トークン",
        token_col: "トークン",
        price_col: "価格",
        change_col: "24時間変化",
        cap_col: "時価総額",
        action_col: "アクション",
        trade_btn: "取引",
        soon_btn: "近日公開",
        wallet_title: "🔐 あなたのウォレット",
        connect_wallet: "ウォレットを接続"
    },
    ko: {
        nav_home: "홈",
        nav_ecosystem: "생태계",
        nav_dashboard: "대시보드",
        hero_badge: "🚀 2026년 출시",
        hero_title1: "탈중앙화",
        hero_title2: "미래의 택시",
        hero_desc: "$TAXI — Solana의 글로벌 택시, 배달, 물류 플랫폼 최초의 토큰. 수익 창출, 투표, 최대 50% 할인 혜택.",
        stat_mcap: "시가총액",
        stat_supply: "총 공급량",
        stat_price: "초기 가격",
        btn_buy: "$TAXI 구매 →",
        btn_learn: "자세히 알아보기",
        features_title1: "왜",
        features_title2: "$TAXI",
        features_title3: "인가요?",
        feature1_title: "즉시 거래",
        feature1_desc: "Solana는 400ms 속도와 $0.001 미만의 수수료 제공",
        feature2_title: "완전한 보안",
        feature2_desc: "Token-2022 표준과 고급 보안 기능",
        feature3_title: "글로벌 생태계",
        feature3_desc: "6개의 위성 토큰이 다양한 지역과 사용 사례에 대응",
        feature4_title: "탈중앙화 거버넌스",
        feature4_desc: "$DHL 보유자가 투표권을 가진 DAO",
        exchange_title1: "생태계 내",
        exchange_title2: "환율",
        exchange1: "팁과 가속",
        exchange2: "스테이킹과 할인",
        exchange3: "DAO 거버넌스",
        exchange4: "비즈니스 클래스",
        solana_powered: "기반",
        footer_desc: "Solana의 탈중앙화 택시 및 배달 플랫폼",
        footer_tokens: "토큰",
        footer_resources: "리소스",
        footer_docs: "문서",
        footer_whitepaper: "백서",
        footer_github: "GitHub",
        footer_contact: "연락처",
        footer_partners: "파트너십",
        footer_rights: "모든 권리 보유.",
        eco_title: "🌍 $TAXI 생태계",
        eco_sub: "6개의 상호 연결된 토큰이 글로벌 탈중앙화 플랫폼 구축",
        taxi_role: "⭐ 메인 생태계 토큰",
        taxi_price: "가격",
        taxi_supply: "공급량",
        taxi_cap: "시가총액",
        taxi_address: "주소",
        taxi_buy: "구매",
        taxi_pools: "풀",
        taxi_staking: "스테이킹",
        sat_title: "🛰️ 위성",
        sat_title2: "토큰",
        uber_desc: "통합 블록체인 익스프레스 라이드 — 스테이킹과 최대 30% 할인. 비즈니스 클래스와 우선 호출 접근.",
        dhl_desc: "탈중앙화 운송 원장 — 생태계 거버넌스. 도시, 수수료, 예산에 대한 투표.",
        tip_desc: "거래 인센티브 프로그램 — 택시, 카페, 레스토랑, 호텔용 범용 팁 토큰.",
        fdx_desc: "연료 거래소 — 2030년 연료 풀, B2B 물류, 탄소 크레딧용 예약.",
        didi_desc: "탈중앙화 스마트 드라이빙 인프라 — 중국과 동아시아의 지역 토큰.",
        grab_desc: "글로벌 라이드 및 앱 기반 — 동남아시아(ASEAN)의 지역 토큰.",
        map_title: "🗺️ 생태계",
        map_title2: "지도",
        regional_title: "🌏 지역",
        regional_title2: "토큰",
        didi_region: "중국, 일본, 한국, 대만",
        grab_region: "싱가포르, 말레이시아, 태국, 베트남, 인도네시아",
        dash_title: "📊 $TAXI",
        dash_title2: "대시보드",
        dash_sub: "실시간 가격, 거래량, 생태계 통계",
        stat_24h: "24시간 거래량",
        stat_holders: "보유자",
        stat_tvl: "TVL",
        chart_title: "📈 $TAXI 가격",
        all_tokens: "전체 생태계",
        all_tokens2: "토큰",
        token_col: "토큰",
        price_col: "가격",
        change_col: "24시간 변화",
        cap_col: "시가총액",
        action_col: "액션",
        trade_btn: "거래",
        soon_btn: "출시 예정",
        wallet_title: "🔐 내 지갑",
        connect_wallet: "지갑 연결"
    },
    vi: {
        nav_home: "Trang chủ",
        nav_ecosystem: "Hệ sinh thái",
        nav_dashboard: "Bảng điều khiển",
        hero_badge: "🚀 Ra mắt 2026",
        hero_title1: "Phi tập trung",
        hero_title2: "Taxi của Tương lai",
        hero_desc: "$TAXI — token đầu tiên trên Solana cho nền tảng taxi, giao hàng và logistics toàn cầu. Kiếm tiền, bỏ phiếu và nhận giảm giá lên đến 50%.",
        stat_mcap: "Vốn hóa",
        stat_supply: "Tổng cung",
        stat_price: "Giá khởi điểm",
        btn_buy: "Mua $TAXI →",
        btn_learn: "Tìm hiểu thêm",
        features_title1: "Tại sao",
        features_title2: "$TAXI",
        features_title3: "?",
        feature1_title: "Giao dịch tức thì",
        feature1_desc: "Solana cung cấp tốc độ 400ms và phí < $0.001",
        feature2_title: "Bảo mật tuyệt đối",
        feature2_desc: "Tiêu chuẩn Token-2022 với tính năng bảo mật nâng cao",
        feature3_title: "Hệ sinh thái toàn cầu",
        feature3_desc: "6 token vệ tinh cho các khu vực và trường hợp sử dụng khác nhau",
        feature4_title: "Quản trị phi tập trung",
        feature4_desc: "DAO với quyền biểu quyết cho người nắm giữ $DHL",
        exchange_title1: "Tỷ giá trong",
        exchange_title2: "Hệ sinh thái",
        exchange1: "Tiền boa & Tăng tốc",
        exchange2: "Staking & Giảm giá",
        exchange3: "Quản trị DAO",
        exchange4: "Hạng thương gia",
        solana_powered: "Được hỗ trợ bởi",
        footer_desc: "Nền tảng taxi và giao hàng phi tập trung trên Solana",
        footer_tokens: "Token",
        footer_resources: "Tài nguyên",
        footer_docs: "Tài liệu",
        footer_whitepaper: "Sách trắng",
        footer_github: "GitHub",
        footer_contact: "Liên hệ",
        footer_partners: "Đối tác",
        footer_rights: "Bảo lưu mọi quyền.",
        eco_title: "🌍 Hệ sinh thái $TAXI",
        eco_sub: "6 token kết nối tạo nền tảng phi tập trung toàn cầu",
        taxi_role: "⭐ Token chính của hệ sinh thái",
        taxi_price: "Giá",
        taxi_supply: "Cung",
        taxi_cap: "Vốn hóa",
        taxi_address: "Địa chỉ",
        taxi_buy: "Mua",
        taxi_pools: "Pool",
        taxi_staking: "Staking",
        sat_title: "🛰️ Vệ tinh",
        sat_title2: "Token",
        uber_desc: "Unified Blockchain Express Ride — staking và giảm giá lên đến 30%. Truy cập hạng thương gia và gọi ưu tiên.",
        dhl_desc: "Decentralized Haul Ledger — quản trị hệ sinh thái. Bỏ phiếu cho thành phố, phí và ngân sách.",
        tip_desc: "Transaction Incentive Program — token tiền boa đa năng cho taxi, quán cà phê, nhà hàng, khách sạn.",
        fdx_desc: "Fuel eXchange — dành riêng cho pool nhiên liệu, logistics B2B và tín chỉ carbon năm 2030.",
        didi_desc: "Decentralized Intelligent Driving Infrastructure — token khu vực cho Trung Quốc và Đông Á.",
        grab_desc: "Global Ride and App-Based — token khu vực cho Đông Nam Á (ASEAN).",
        map_title: "🗺️ Hệ sinh thái",
        map_title2: "Bản đồ",
        regional_title: "🌏 Khu vực",
        regional_title2: "Token",
        didi_region: "Trung Quốc, Nhật Bản, Hàn Quốc, Đài Loan",
        grab_region: "Singapore, Malaysia, Thái Lan, Việt Nam, Indonesia",
        dash_title: "📊 $TAXI",
        dash_title2: "Bảng điều khiển",
        dash_sub: "Giá, khối lượng và thống kê hệ sinh thái theo thời gian thực",
        stat_24h: "Khối lượng 24h",
        stat_holders: "Người nắm giữ",
        stat_tvl: "TVL",
        chart_title: "📈 Giá $TAXI",
        all_tokens: "Tất cả token",
        all_tokens2: "hệ sinh thái",
        token_col: "Token",
        price_col: "Giá",
        change_col: "24h %",
        cap_col: "Vốn hóa",
        action_col: "Hành động",
        trade_btn: "Giao dịch",
        soon_btn: "Sắp ra mắt",
        wallet_title: "🔐 Ví của bạn",
        connect_wallet: "Kết nối ví"
    },
    th: {
        nav_home: "หน้าหลัก",
        nav_ecosystem: "ระบบนิเวศ",
        nav_dashboard: "แดชบอร์ด",
        hero_badge: "🚀 เปิดตัว 2026",
        hero_title1: "แบบกระจายอำนาจ",
        hero_title2: "แท็กซี่แห่งอนาคต",
        hero_desc: "$TAXI — โทเค็นแรกบน Solana สำหรับแพลตฟอร์มแท็กซี่ จัดส่ง และโลจิสติกส์ระดับโลก รับรายได้ โหวต และรับส่วนลดสูงสุด 50%",
        stat_mcap: "มูลค่าตลาด",
        stat_supply: "อุปทานทั้งหมด",
        stat_price: "ราคาเริ่มต้น",
        btn_buy: "ซื้อ $TAXI →",
        btn_learn: "เรียนรู้เพิ่มเติม",
        features_title1: "ทำไม",
        features_title2: "$TAXI",
        features_title3: "?",
        feature1_title: "ธุรกรรมทันที",
        feature1_desc: "Solana ให้ความเร็ว 400ms และค่าธรรมเนียม < $0.001",
        feature2_title: "ความปลอดภัยเต็มรูปแบบ",
        feature2_desc: "มาตรฐาน Token-2022 พร้อมฟีเจอร์ความปลอดภัยขั้นสูง",
        feature3_title: "ระบบนิเวศระดับโลก",
        feature3_desc: "6 โทเค็นดาวเทียมสำหรับภูมิภาคและกรณีการใช้งานต่างๆ",
        feature4_title: "การกำกับดูแลแบบกระจายอำนาจ",
        feature4_desc: "DAO พร้อมสิทธิ์ออกเสียงสำหรับผู้ถือ $DHL",
        exchange_title1: "อัตราแลกเปลี่ยนใน",
        exchange_title2: "ระบบนิเวศ",
        exchange1: "ทิปและการเร่งความเร็ว",
        exchange2: "การ Stake และส่วนลด",
        exchange3: "การกำกับดูแล DAO",
        exchange4: "ชั้นธุรกิจ",
        solana_powered: "ขับเคลื่อนโดย",
        footer_desc: "แพลตฟอร์มแท็กซี่และจัดส่งแบบกระจายอำนาจบน Solana",
        footer_tokens: "โทเค็น",
        footer_resources: "ทรัพยากร",
        footer_docs: "เอกสาร",
        footer_whitepaper: "สมุดปกขาว",
        footer_github: "GitHub",
        footer_contact: "ติดต่อ",
        footer_partners: "พันธมิตร",
        footer_rights: "สงวนลิขสิทธิ์.",
        eco_title: "🌍 ระบบนิเวศ $TAXI",
        eco_sub: "6 โทเค็นที่เชื่อมต่อกันสร้างแพลตฟอร์มแบบกระจายอำนาจระดับโลก",
        taxi_role: "⭐ โทเค็นหลักของระบบนิเวศ",
        taxi_price: "ราคา",
        taxi_supply: "อุปทาน",
        taxi_cap: "มูลค่าตลาด",
        taxi_address: "ที่อยู่",
        taxi_buy: "ซื้อ",
        taxi_pools: "Pool",
        taxi_staking: "Staking",
        sat_title: "🛰️ ดาวเทียม",
        sat_title2: "โทเค็น",
        uber_desc: "Unified Blockchain Express Ride — Stake และรับส่วนลดสูงสุด 30%. เข้าถึงชั้นธุรกิจและการเรียก優先",
        dhl_desc: "Decentralized Haul Ledger — การกำกับดูแลระบบนิเวศ โหวตสำหรับเมือง ค่าธรรมเนียม และงบประมาณ",
        tip_desc: "Transaction Incentive Program — โทเค็นทิปอเนกประสงค์สำหรับแท็กซี่ ร้านกาแฟ ร้านอาหาร โรงแรม",
        fdx_desc: "Fuel eXchange — สงวนไว้สำหรับ pool เชื้อเพลิง โลจิสติกส์ B2B และเครดิตคาร์บอนในปี 2030",
        didi_desc: "Decentralized Intelligent Driving Infrastructure — โทเค็นระดับภูมิภาคสำหรับจีนและเอเชียตะวันออก",
        grab_desc: "Global Ride and App-Based — โทเค็นระดับภูมิภาคสำหรับเอเชียตะวันออกเฉียงใต้ (อาเซียน)",
        map_title: "🗺️ ระบบนิเวศ",
        map_title2: "แผนที่",
        regional_title: "🌏 ภูมิภาค",
        regional_title2: "โทเค็น",
        didi_region: "จีน ญี่ปุ่น เกาหลี ไต้หวัน",
        grab_region: "สิงคโปร์ มาเลเซีย ไทย เวียดnam อินโดนีเซีย",
        dash_title: "📊 $TAXI",
        dash_title2: "แดชบอร์ด",
        dash_sub: "ราคา ปริมาณ และสถิติระบบนิเวศแบบเรียลไทม์",
        stat_24h: "ปริมาณ 24ชม.",
        stat_holders: "ผู้ถือ",
        stat_tvl: "TVL",
        chart_title: "📈 ราคา $TAXI",
        all_tokens: "โทเค็นทั้งหมด",
        all_tokens2: "ในระบบนิเวศ",
        token_col: "โทเค็น",
        price_col: "ราคา",
        change_col: "24ชม. %",
        cap_col: "มูลค่าตลาด",
        action_col: "ดำเนินการ",
        trade_btn: "เทรด",
        soon_btn: "เร็วๆนี้",
        wallet_title: "🔐 กระเป๋าเงินของคุณ",
        connect_wallet: "เชื่อมต่อกระเป๋าเงิน"
    },
    ms: {
        nav_home: "Utama",
        nav_ecosystem: "Ekosistem",
        nav_dashboard: "Papan Pemuka",
        hero_badge: "🚀 Lancaran 2026",
        hero_title1: "Terpencar",
        hero_title2: "Teksi Masa Depan",
        hero_desc: "$TAXI — token pertama di Solana untuk platform teksi, penghantaran, dan logistik global. Dapatkan pendapatan, undi, dan dapatkan diskaun sehingga 50%.",
        stat_mcap: "Permodalan Pasaran",
        stat_supply: "Bekalan Jumlah",
        stat_price: "Harga Permulaan",
        btn_buy: "Beli $TAXI →",
        btn_learn: "Ketahui Lebih Lanjut",
        features_title1: "Mengapa",
        features_title2: "$TAXI",
        features_title3: "?",
        feature1_title: "Transaksi Segera",
        feature1_desc: "Solana memberikan kelajuan 400ms dan yuran < $0.001",
        feature2_title: "Keselamatan Penuh",
        feature2_desc: "Standard Token-2022 dengan ciri keselamatan lanjutan",
        feature3_title: "Ekosistem Global",
        feature3_desc: "6 token satelit untuk pelbagai wilayah dan kes penggunaan",
        feature4_title: "Tadbir Urus Terpencar",
        feature4_desc: "DAO dengan hak mengundi untuk pemegang $DHL",
        exchange_title1: "Kadar Tukaran dalam",
        exchange_title2: "Ekosistem",
        exchange1: "Tip & Pecutan",
        exchange2: "Staking & Diskaun",
        exchange3: "Tadbir Urus DAO",
        exchange4: "Kelas Perniagaan",
        solana_powered: "Dikuasakan oleh",
        footer_desc: "Platform teksi dan penghantaran terpencar di Solana",
        footer_tokens: "Token",
        footer_resources: "Sumber",
        footer_docs: "Dokumentasi",
        footer_whitepaper: "Kertas Putih",
        footer_github: "GitHub",
        footer_contact: "Hubungi",
        footer_partners: "Perkongsian",
        footer_rights: "Hak cipta terpelihara.",
        eco_title: "🌍 Ekosistem $TAXI",
        eco_sub: "6 token yang saling berkaitan membina platform terpencar global",
        taxi_role: "⭐ Token Utama Ekosistem",
        taxi_price: "Harga",
        taxi_supply: "Bekalan",
        taxi_cap: "Permodalan Pasaran",
        taxi_address: "Alamat",
        taxi_buy: "Beli",
        taxi_pools: "Pool",
        taxi_staking: "Staking",
        sat_title: "🛰️ Satelit",
        sat_title2: "Token",
        uber_desc: "Unified Blockchain Express Ride — staking dan diskaun sehingga 30%. Akses ke kelas perniagaan dan panggilan keutamaan.",
        dhl_desc: "Decentralized Haul Ledger — tadbir urus ekosistem. Undi untuk bandar, yuran, dan belanjawan.",
        tip_desc: "Transaction Incentive Program — token tip serba guna untuk teksi, kafe, restoran, hotel.",
        fdx_desc: "Fuel eXchange — dikhaskan untuk pool bahan api, logistik B2B, dan kredit karbon pada tahun 2030.",
        didi_desc: "Decentralized Intelligent Driving Infrastructure — token serantau untuk China dan Asia Timur.",
        grab_desc: "Global Ride and App-Based — token serantau untuk Asia Tenggara (ASEAN).",
        map_title: "🗺️ Ekosistem",
        map_title2: "Peta",
        regional_title: "🌏 Serantau",
        regional_title2: "Token",
        didi_region: "China, Jepun, Korea, Taiwan",
        grab_region: "Singapura, Malaysia, Thailand, Vietnam, Indonesia",
        dash_title: "📊 $TAXI",
        dash_title2: "Papan Pemuka",
        dash_sub: "Harga, volum, dan statistik ekosistem masa nyata",
        stat_24h: "Volum 24j",
        stat_holders: "Pemegang",
        stat_tvl: "TVL",
        chart_title: "📈 Harga $TAXI",
        all_tokens: "Semua Token",
        all_tokens2: "Ekosistem",
        token_col: "Token",
        price_col: "Harga",
        change_col: "24j %",
        cap_col: "Permodalan Pasaran",
        action_col: "Tindakan",
        trade_btn: "Dagang",
        soon_btn: "Akan Datang",
        wallet_title: "🔐 Dompet Anda",
        connect_wallet: "Sambung Dompet"
    },
    id: {
        nav_home: "Beranda",
        nav_ecosystem: "Ekosistem",
        nav_dashboard: "Dasbor",
        hero_badge: "🚀 Peluncuran 2026",
        hero_title1: "Terdesentralisasi",
        hero_title2: "Taksi Masa Depan",
        hero_desc: "$TAXI — token pertama di Solana untuk platform taksi, pengiriman, dan logistik global. Dapatkan pendapatan, beri suara, dan dapatkan diskon hingga 50%.",
        stat_mcap: "Kapitalisasi Pasar",
        stat_supply: "Total Pasokan",
        stat_price: "Harga Awal",
        btn_buy: "Beli $TAXI →",
        btn_learn: "Pelajari Lebih Lanjut",
        features_title1: "Mengapa",
        features_title2: "$TAXI",
        features_title3: "?",
        feature1_title: "Transaksi Instan",
        feature1_desc: "Solana memberikan kecepatan 400ms dan biaya < $0.001",
        feature2_title: "Keamanan Penuh",
        feature2_desc: "Standar Token-2022 dengan fitur keamanan canggih",
        feature3_title: "Ekosistem Global",
        feature3_desc: "6 token satelit untuk berbagai wilayah dan kasus penggunaan",
        feature4_title: "Tata Kelola Terdesentralisasi",
        feature4_desc: "DAO dengan hak suara untuk pemegang $DHL",
        exchange_title1: "Nilai Tukar dalam",
        exchange_title2: "Ekosistem",
        exchange1: "Tip & Akselerasi",
        exchange2: "Staking & Diskon",
        exchange3: "Tata Kelola DAO",
        exchange4: "Kelas Bisnis",
        solana_powered: "Didukung oleh",
        footer_desc: "Platform taksi dan pengiriman terdesentralisasi di Solana",
        footer_tokens: "Token",
        footer_resources: "Sumber Daya",
        footer_docs: "Dokumentasi",
        footer_whitepaper: "Whitepaper",
        footer_github: "GitHub",
        footer_contact: "Kontak",
        footer_partners: "Kemitraan",
        footer_rights: "Hak cipta dilindungi.",
        eco_title: "🌍 Ekosistem $TAXI",
        eco_sub: "6 token yang saling terhubung membangun platform terdesentralisasi global",
        taxi_role: "⭐ Token Utama Ekosistem",
        taxi_price: "Harga",
        taxi_supply: "Pasokan",
        taxi_cap: "Kapitalisasi Pasar",
        taxi_address: "Alamat",
        taxi_buy: "Beli",
        taxi_pools: "Pool",
        taxi_staking: "Staking",
        sat_title: "🛰️ Satelit",
        sat_title2: "Token",
        uber_desc: "Unified Blockchain Express Ride — staking dan diskon hingga 30%. Akses ke kelas bisnis dan panggilan prioritas.",
        dhl_desc: "Decentralized Haul Ledger — tata kelola ekosistem. Voting untuk kota, biaya, dan anggaran.",
        tip_desc: "Transaction Incentive Program — token tip serbaguna untuk taksi, kafe, restoran, hotel.",
        fdx_desc: "Fuel eXchange — disediakan untuk pool bahan bakar, logistik B2B, dan kredit karbon tahun 2030.",
        didi_desc: "Decentralized Intelligent Driving Infrastructure — token regional untuk China dan Asia Timur.",
        grab_desc: "Global Ride and App-Based — token regional untuk Asia Tenggara (ASEAN).",
        map_title: "🗺️ Ekosistem",
        map_title2: "Peta",
        regional_title: "🌏 Regional",
        regional_title2: "Token",
        didi_region: "China, Jepang, Korea, Taiwan",
        grab_region: "Singapura, Malaysia, Thailand, Vietnam, Indonesia",
        dash_title: "📊 $TAXI",
        dash_title2: "Dasbor",
        dash_sub: "Harga, volume, dan statistik ekosistem real-time",
        stat_24h: "Volume 24j",
        stat_holders: "Pemegang",
        stat_tvl: "TVL",
        chart_title: "📈 Harga $TAXI",
        all_tokens: "Semua Token",
        all_tokens2: "Ekosistem",
        token_col: "Token",
        price_col: "Harga",
        change_col: "24j %",
        cap_col: "Kapitalisasi Pasar",
        action_col: "Aksi",
        trade_btn: "Trading",
        soon_btn: "Segera",
        wallet_title: "🔐 Dompet Anda",
        connect_wallet: "Hubungkan Dompet"
    },
    es: {
        nav_home: "Inicio",
        nav_ecosystem: "Ecosistema",
        nav_dashboard: "Panel",
        hero_badge: "🚀 Lanzamiento 2026",
        hero_title1: "Descentralizado",
        hero_title2: "Taxi del Futuro",
        hero_desc: "$TAXI — el primer token en Solana para una plataforma global de taxis, entregas y logística. Gana, vota y obtén hasta un 50% de descuento.",
        stat_mcap: "Capitalización",
        stat_supply: "Suministro Total",
        stat_price: "Precio Inicial",
        btn_buy: "Comprar $TAXI →",
        btn_learn: "Más Información",
        features_title1: "¿Por qué",
        features_title2: "$TAXI",
        features_title3: "?",
        feature1_title: "Transacciones Instantáneas",
        feature1_desc: "Solana ofrece velocidad de 400ms y comisiones < $0.001",
        feature2_title: "Seguridad Total",
        feature2_desc: "Estándar Token-2022 con funciones avanzadas de seguridad",
        feature3_title: "Ecosistema Global",
        feature3_desc: "6 tokens satélite para diferentes regiones y casos de uso",
        feature4_title: "Gobernanza Descentralizada",
        feature4_desc: "DAO con derechos de voto para tenedores de $DHL",
        exchange_title1: "Tipos de Cambio en",
        exchange_title2: "el Ecosistema",
        exchange1: "Propinas y Aceleración",
        exchange2: "Staking y Descuentos",
        exchange3: "Gobernanza DAO",
        exchange4: "Clase Business",
        solana_powered: "Impulsado por",
        footer_desc: "Plataforma descentralizada de taxis y entregas en Solana",
        footer_tokens: "Tokens",
        footer_resources: "Recursos",
        footer_docs: "Documentación",
        footer_whitepaper: "Whitepaper",
        footer_github: "GitHub",
        footer_contact: "Contacto",
        footer_partners: "Asociaciones",
        footer_rights: "Todos los derechos reservados.",
        eco_title: "🌍 Ecosistema $TAXI",
        eco_sub: "6 tokens interconectados para una plataforma descentralizada global",
        taxi_role: "⭐ Token Principal del Ecosistema",
        taxi_price: "Precio",
        taxi_supply: "Suministro",
        taxi_cap: "Capitalización",
        taxi_address: "Dirección",
        taxi_buy: "Comprar",
        taxi_pools: "Pools",
        taxi_staking: "Staking",
        sat_title: "🛰️ Satélite",
        sat_title2: "Tokens",
        uber_desc: "Unified Blockchain Express Ride — staking y hasta 30% de descuento. Acceso a clase business y llamadas prioritarias.",
        dhl_desc: "Decentralized Haul Ledger — gobernanza del ecosistema. Votación para ciudades, comisiones y presupuesto.",
        tip_desc: "Transaction Incentive Program — token de propinas universal para taxis, cafeterías, restaurantes, hoteles.",
        fdx_desc: "Fuel eXchange — reservado para pools de combustible, logística B2B y créditos de carbono en 2030.",
        didi_desc: "Decentralized Intelligent Driving Infrastructure — token regional para China y Asia Oriental.",
        grab_desc: "Global Ride and App-Based — token regional para el Sudeste Asiático (ASEAN).",
        map_title: "🗺️ Ecosistema",
        map_title2: "Mapa",
        regional_title: "🌏 Regional",
        regional_title2: "Tokens",
        didi_region: "China, Japón, Corea, Taiwán",
        grab_region: "Singapur, Malasia, Tailandia, Vietnam, Indonesia",
        dash_title: "📊 $TAXI",
        dash_title2: "Panel",
        dash_sub: "Precios, volúmenes y estadísticas del ecosistema en tiempo real",
        stat_24h: "Volumen 24h",
        stat_holders: "Tenedores",
        stat_tvl: "TVL",
        chart_title: "📈 Precio de $TAXI",
        all_tokens: "Todos los Tokens",
        all_tokens2: "del Ecosistema",
        token_col: "Token",
        price_col: "Precio",
        change_col: "24h %",
        cap_col: "Capitalización",
        action_col: "Acción",
        trade_btn: "Comerciar",
        soon_btn: "Pronto",
        wallet_title: "🔐 Tu Cartera",
        connect_wallet: "Conectar Cartera"
    },
    ru: {
        nav_home: "Главная",
        nav_ecosystem: "Экосистема",
        nav_dashboard: "Дашборд",
        hero_badge: "🚀 Запуск 2026",
        hero_title1: "Децентрализованное",
        hero_title2: "Такси будущего",
        hero_desc: "$TAXI — первый токен на Solana для глобальной платформы такси, доставки и логистики. Зарабатывай, голосуй и получай скидки до 50%.",
        stat_mcap: "Капитализация",
        stat_supply: "Общий объём",
        stat_price: "Начальная цена",
        btn_buy: "Купить $TAXI →",
        btn_learn: "Узнать больше",
        features_title1: "Почему",
        features_title2: "$TAXI",
        features_title3: "?",
        feature1_title: "Мгновенные транзакции",
        feature1_desc: "Solana обеспечивает скорость 400мс и комиссию < $0.001",
        feature2_title: "Полная безопасность",
        feature2_desc: "Стандарт Token-2022 с расширенными функциями защиты",
        feature3_title: "Глобальная экосистема",
        feature3_desc: "6 сателлитных токенов для разных регионов и задач",
        feature4_title: "Децентрализованное управление",
        feature4_desc: "DAO с правом голоса для держателей $DHL",
        exchange_title1: "Курсы обмена в",
        exchange_title2: "экосистеме",
        exchange1: "Чаевые и ускорение",
        exchange2: "Стейкинг и скидки",
        exchange3: "DAO управление",
        exchange4: "Бизнес-класс",
        solana_powered: "Работает на",
        footer_desc: "Децентрализованная платформа такси и доставки на Solana",
        footer_tokens: "Токены",
        footer_resources: "Ресурсы",
        footer_docs: "Документация",
        footer_whitepaper: "Whitepaper",
        footer_github: "GitHub",
        footer_contact: "Контакты",
        footer_partners: "Партнерство",
        footer_rights: "Все права защищены.",
        eco_title: "🌍 Экосистема $TAXI",
        eco_sub: "6 взаимосвязанных токенов для глобальной децентрализованной платформы",
        taxi_role: "⭐ Основной токен экосистемы",
        taxi_price: "Цена",
        taxi_supply: "Объём",
        taxi_cap: "Капитализация",
        taxi_address: "Адрес",
        taxi_buy: "Купить",
        taxi_pools: "Пулы",
        taxi_staking: "Стейкинг",
        sat_title: "🛰️ Сателлитные",
        sat_title2: "токены",
        uber_desc: "Unified Blockchain Express Ride — стейкинг и скидки до 30%. Доступ к бизнес-классу и приоритетному вызову.",
        dhl_desc: "Decentralized Haul Ledger — управление экосистемой. Голосование за города, комиссии и бюджет.",
        tip_desc: "Transaction Incentive Program — универсальный токен чаевых для такси, кафе, ресторанов, отелей.",
        fdx_desc: "Fuel eXchange — зарезервирован для топливных пулов, B2B-логистики и карбоновых кредитов в 2030.",
        didi_desc: "Decentralized Intelligent Driving Infrastructure — региональный токен для Китая и Восточной Азии.",
        grab_desc: "Global Ride and App-Based — региональный токен для Юго-Восточной Азии (АСЕАН).",
        map_title: "🗺️ Экосистема",
        map_title2: "Карта",
        regional_title: "🌏 Региональные",
        regional_title2: "токены",
        didi_region: "Китай, Япония, Корея, Тайвань",
        grab_region: "Сингапур, Малайзия, Таиланд, Вьетнам, Индонезия",
        dash_title: "📊 $TAXI",
        dash_title2: "Дашборд",
        dash_sub: "Цены, объёмы и статистика экосистемы в реальном времени",
        stat_24h: "Объём за 24ч",
        stat_holders: "Держатели",
        stat_tvl: "TVL",
        chart_title: "📈 Цена $TAXI",
        all_tokens: "Все токены",
        all_tokens2: "экосистемы",
        token_col: "Токен",
        price_col: "Цена",
        change_col: "24ч %",
        cap_col: "Капитализация",
        action_col: "Действие",
        trade_btn: "Торговать",
        soon_btn: "Скоро",
        wallet_title: "🔐 Ваш кошелек",
        connect_wallet: "Подключить кошелек"
    },
    ar: {
        nav_home: "الرئيسية",
        nav_ecosystem: "النظام البيئي",
        nav_dashboard: "لوحة التحكم",
        hero_badge: "🚀 الإطلاق 2026",
        hero_title1: "لامركزي",
        hero_title2: "تاكسي المستقبل",
        hero_desc: "$TAXI — أول رمز على Solana لمنصة عالمية للتاكسي والتوصيل والخدمات اللوجستية. اكسب وصوّت واحصل على خصومات تصل إلى 50%.",
        stat_mcap: "القيمة السوقية",
        stat_supply: "إجمالي العرض",
        stat_price: "السعر الابتدائي",
        btn_buy: "شراء $TAXI →",
        btn_learn: "اعرف المزيد",
        features_title1: "لماذا",
        features_title2: "$TAXI",
        features_title3: "؟",
        feature1_title: "معاملات فورية",
        feature1_desc: "Solana توفر سرعة 400ms ورسوم < $0.001",
        feature2_title: "أمان كامل",
        feature2_desc: "معيار Token-2022 مع ميزات أمان متقدمة",
        feature3_title: "نظام بيئي عالمي",
        feature3_desc: "6 رموز تابعة لمناطق وحالات استخدام مختلفة",
        feature4_title: "حوكمة لامركزية",
        feature4_desc: "DAO مع حقوق التصويت لحاملي $DHL",
        exchange_title1: "أسعار الصرف في",
        exchange_title2: "النظام البيئي",
        exchange1: "الإكراميات والتسريع",
        exchange2: "التخزين والخصومات",
        exchange3: "حوكمة DAO",
        exchange4: "درجة الأعمال",
        solana_powered: "مدعوم من",
        footer_desc: "منصة تاكسي وتوصيل لامركزية على Solana",
        footer_tokens: "الرموز",
        footer_resources: "الموارد",
        footer_docs: "الوثائق",
        footer_whitepaper: "الورقة البيضاء",
        footer_github: "GitHub",
        footer_contact: "اتصل بنا",
        footer_partners: "الشراكات",
        footer_rights: "جميع الحقوق محفوظة.",
        eco_title: "🌍 نظام $TAXI البيئي",
        eco_sub: "6 رموز مترابطة لبناء منصة لامركزية عالمية",
        taxi_role: "⭐ الرمز الرئيسي للنظام البيئي",
        taxi_price: "السعر",
        taxi_supply: "العرض",
        taxi_cap: "القيمة السوقية",
        taxi_address: "العنوان",
        taxi_buy: "شراء",
        taxi_pools: "المجمعات",
        taxi_staking: "التخزين",
        sat_title: "🛰️ التابع",
        sat_title2: "الرموز",
        uber_desc: "Unified Blockchain Express Ride — التخزين وخصومات تصل إلى 30%. الوصول إلى درجة الأعمال والمكالمات ذات الأولوية.",
        dhl_desc: "Decentralized Haul Ledger — حوكمة النظام البيئي. التصويت للمدن والرسوم والميزانية.",
        tip_desc: "Transaction Incentive Program — رمز الإكراميات الشامل للتاكسي والمقاهي والمطاعم والفنادق.",
        fdx_desc: "Fuel eXchange — محجوز لمجمعات الوقود واللوجستيات B2B وأرصدة الكربون في 2030.",
        didi_desc: "Decentralized Intelligent Driving Infrastructure — الرمز الإقليمي للصين وشرق آسيا.",
        grab_desc: "Global Ride and App-Based — الرمز الإقليمي لجنوب شرق آسيا (آسيان).",
        map_title: "🗺️ النظام البيئي",
        map_title2: "الخريطة",
        regional_title: "🌏 الإقليمي",
        regional_title2: "الرموز",
        didi_region: "الصين واليابان وكوريا وتايوان",
        grab_region: "سنغافورة وماليزيا وتايلاند وفيتنام وإندونيسيا",
        dash_title: "📊 $TAXI",
        dash_title2: "لوحة التحكم",
        dash_sub: "الأسعار والأحجام وإحصائيات النظام البيئي في الوقت الفعلي",
        stat_24h: "حجم 24 ساعة",
        stat_holders: "الحاملون",
        stat_tvl: "TVL",
        chart_title: "📈 سعر $TAXI",
        all_tokens: "جميع رموز",
        all_tokens2: "النظام البيئي",
        token_col: "الرمز",
        price_col: "السعر",
        change_col: "تغيير 24 ساعة",
        cap_col: "القيمة السوقية",
        action_col: "الإجراء",
        trade_btn: "تداول",
        soon_btn: "قريباً",
        wallet_title: "🔐 محفظتك",
        connect_wallet: "ربط المحفظة"
    }
};

let currentLanguage = 'en';

function setLanguage(lang) {
    currentLanguage = lang;
    localStorage.setItem('taxi_language', lang);
    updateUI(lang);
    document.getElementById('currentLangLabel').textContent = lang.toUpperCase();
    document.getElementById('langDropdown').classList.remove('show');
}

function updateUI(lang) {
    const elements = document.querySelectorAll('[data-i18n]');
    elements.forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (translations[lang] && translations[lang][key]) {
            el.textContent = translations[lang][key];
        }
    });
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
}

function toggleLanguages() {
    const dropdown = document.getElementById('langDropdown');
    dropdown.classList.toggle('show');
}

document.addEventListener('click', function(event) {
    const dropdown = document.getElementById('langDropdown');
    const btn = document.querySelector('.lang-btn');
    if (btn && !btn.contains(event.target) && dropdown && !dropdown.contains(event.target)) {
        dropdown.classList.remove('show');
    }
});

document.addEventListener('DOMContentLoaded', function() {
    const savedLang = localStorage.getItem('taxi_language') || 'en';
    setLanguage(savedLang);
});
